/*
  Copyright (c) 2025 zhengxyz123

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/*
  Load resource pack and use assets in it.

  resource pack is generated by `tools/respack.py`.
*/

#include "respack.h"
#include <stdlib.h>
#include <string.h>

/*
  The `fnv_32a_str` function from
  https://github.com/lcn2/fnv/blob/master/hash_32a.c
*/
uint32_t fnv1a_32(char* str, uint32_t hval) {
    unsigned char* s = (unsigned char*)str;
    while (*s) {
        hval ^= (uint32_t)*s++;
#if defined(NO_FNV_GCC_OPTIMIZATION)
        hval *= FNV1_32_PRIME;
#else
        hval += (hval << 1) + (hval << 4) + (hval << 7) + (hval << 8) +
                (hval << 24);
#endif
    }
    return hval;
}

Respack* LoadRespack(char* filename) {
    Respack* rpkg = calloc(1, sizeof(Respack));
    rpkg->fp = fopen(filename, "rb");
    if (!rpkg->fp) {
        free(rpkg);
        return NULL;
    }
    fread(&rpkg->header, sizeof(RespackHeader), 1, rpkg->fp);
    if (feof(rpkg->fp) || ferror(rpkg->fp)) {
        goto error0;
    }
    if (strncmp(rpkg->header.magic, "RPKG", 4) != 0) {
        goto error0;
    }
    if (rpkg->header.version != 1) {
        goto error0;
    }
    rpkg->entries = calloc(rpkg->header.entry_count, sizeof(RespackEntry));
    for (size_t i = 0; i < rpkg->header.entry_count; ++i) {
        fread(&rpkg->entries[i], sizeof(RespackEntry), 1, rpkg->fp);
        if (feof(rpkg->fp) || ferror(rpkg->fp)) {
            goto error1;
        }
    }
    return rpkg;
error1:
    free(rpkg->entries);
error0:
    fclose(rpkg->fp);
    free(rpkg);
    return NULL;
}

int RespackHasItem(Respack* rpkg, char* key, size_t* index) {
    uint32_t hash = fnv1a_32(key, FNV1_32_INIT);
    int found = 0, count = 0;
    for (size_t i = 0; i < rpkg->header.entry_count; ++i) {
        if (rpkg->entries[i].key_hash == hash) {
            found = 1;
            if (index) {
                *index = i;
            }
            ++count;
        }
    }
    if (count <= 1) {
        return found;
    }
    // in 99.99% cases, the following for loop will not execute
    for (size_t i = 0; i < rpkg->header.entry_count; ++i) {
        RespackEntry* entry = &rpkg->entries[i];
        fseek(
            rpkg->fp, rpkg->header.key_index_offset + entry->key_offset,
            SEEK_SET
        );
        char* s = calloc(entry->key_length, sizeof(char));
        fread(s, sizeof(char), entry->key_length, rpkg->fp);
        if (strncmp(key, s, entry->key_length) == 0) {
            free(s);
            if (index) {
                *index = i;
            }
            return 1;
        }
        free(s);
    }
    return 0;
}

/*
  Load the asset named `key` from the resource pack `rpkg`.

  `length` is a pointer filled with length of asset, can be `NULL`.
  Returns a pointer to the asset's address.

  If `length==0` or the return value is `NULL`, the asset may not exist or the
  resource pack format may be invalid.
*/
void* RespackGetItem(Respack* rpkg, char* key, size_t* length) {
    size_t index;
    if (!RespackHasItem(rpkg, key, &index)) {
        if (length) {
            length = 0;
        }
        return NULL;
    }
    RespackEntry* entry = &rpkg->entries[index];
    void* data = calloc(entry->value_length, 1);
    fseek(
        rpkg->fp, rpkg->header.value_index_offset + entry->value_offset,
        SEEK_SET
    );
    fread(data, 1, entry->value_length, rpkg->fp);
    if (feof(rpkg->fp) || ferror(rpkg->fp)) {
        if (length) {
            length = 0;
        }
        return NULL;
    }
    *length = entry->value_length;
    return data;
}

void FreeRespack(Respack* rpkg) {
    fclose(rpkg->fp);
    free(rpkg->entries);
    free(rpkg);
}
