/*
  Copyright (c) 2025 zhengxyz123

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/*
  Binary format of a map file (generated by tools/map_editor.py):

  +----------------+-------+-----------------+--------------------------+
  | Part           | Size  | Type            | Description              |
  +================+=======+=================+==========================+
  | File header    | 1     | char[3]         | Must be 0x4d4150 ("MAP") |
  +----------------+-------+-----------------+--------------------------+
  | Version        | 1     | char            | Always be 1              |
  +----------------+-------+-----------------+--------------------------+
  | Animated tiles | 1     | unsigned short  | As the name said         |
  | count (size1)  |       |                 |                          |
  +----------------+-------+-----------------+--------------------------+
  | Animated tile  | size1 | AnimatedTile[]  | The section where store  |
  | array          |       |                 | the animated tiles       |
  +----------------+-------+-----------------+--------------------------+
  | Objects count  | 1     | unsigned short  | As the name said         |
  | (size2)        |       |                 |                          |
  +----------------+-------+-----------------+--------------------------+
  | Objects array  | size2 | TileMapObject[] | Store all objects in the |
  |                |       |                 | tile map                 |
  +----------------+-------+-----------------+--------------------------+
  | Layers count   | 1     | unsigned short  | As the name said         |
  | (size3)        |       |                 |                          |
  +----------------+-------+-----------------+--------------------------+
  | Layers array   | size3 | TileMapLayer[]  | The array stores all     |
  |                |       |                 | layers in the tile map   |
  +----------------+-------+-----------------+--------------------------+
*/

#include "tilemap.h"
#include "../resources/assets.h"
#include "../resources/loader.h"

TileSet* default_tileset = NULL;

void InitMapSystem() {
    default_tileset = (TileSet*)malloc(sizeof(TileSet));
    default_tileset->texture =
        LoadTexture(tilesets_png_content, sizeof(tilesets_png_content));
    default_tileset->first_index = 1;
}

void QuitMapSystem() {
    SDL_DestroyTexture(default_tileset->texture);
    free(default_tileset);
}

TileMap* LoadTileMap(const unsigned char* data, size_t size) {
    TileMap* map = (TileMap*)calloc(1, sizeof(TileMap));
    map->tile_width = 32;
    map->tile_height = 32;
    map->tileset_count = 1;
    map->tileset = default_tileset;
    SDL_RWops* map_data = SDL_RWFromConstMem(data, size);
    char header[4];
    SDL_RWread(map_data, header, sizeof(char), 4);
    if (header[0] != 'M' || header[1] != 'A' || header[2] != 'P' || header[3] != 1) {
        SDL_RWclose(map_data);
        return NULL;
    }
    unsigned short anim_tile_count;
    SDL_RWread(map_data, &anim_tile_count, sizeof(unsigned short), 1);
    map->anim_tile_count = anim_tile_count;
    map->anim_tile =
        (AnimatedTileSet*)calloc(anim_tile_count, sizeof(AnimatedTileSet));
    for (size_t i = 0; i < map->anim_tile_count; ++i) {
        unsigned char is_playing;
        SDL_RWread(map_data, &is_playing, sizeof(unsigned char), 1);
        map->anim_tile[i].is_playing = is_playing;
        unsigned short count;
        SDL_RWread(map_data, &count, sizeof(unsigned short), 1);
        map->anim_tile[i].count = count;
        map->anim_tile[i].frames = (SDL_Rect*)calloc(count, sizeof(SDL_Rect));
        for (size_t j = 0; j < map->anim_tile[i].count; ++j) {
            short rect[4];
            SDL_RWread(map_data, rect, sizeof(short), 4);
            map->anim_tile[i].frames[j] =
                (SDL_Rect){rect[0], rect[1], rect[2], rect[3]};
        }
    }
    SDL_RWclose(map_data);
    return map;
}

void FreeTileMap(TileMap* map) {
    for (size_t i = 0; i < map->anim_tile_count; ++i) {
        free(map->anim_tile[i].frames);
    }
    free(map->anim_tile);
    free(map);
}
