/*
  Copyright (c) 2025 zhengxyz123

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/*
  Binary format of a map file (generated by tools/map_editor.py):

  +--------+-----------------+------+------------------------------+
  | Offset | Data Type       | Size | Description                  |
  +========+=================+======+==============================+
  | 0      | char[3]         | 3    | File header 0x4d5150 ("MAP") |
  +--------+-----------------+------+------------------------------+
  | 3      | unsigned char   | 1    | Version (always be 1)        |
  +--------+-----------------+------+------------------------------+
  | 4      | unsigned short  | 2    | Tile width (always be 32)    |
  +--------+-----------------+------+------------------------------+
  | 6      | unsigned short  | 2    | Tile height (always be 32)   |
  +--------+-----------------+------+------------------------------+
  | 8      | unsigned short  | 2    | Animated tile count          |
  +--------+-----------------+------+------------------------------+
  | 10     | unsigned short  | 2    | Tile map object count        |
  +--------+-----------------+------+------------------------------+
  | 12     | unsigned short  | 2    | Tile map layer count         |
  +--------+-----------------+------+------------------------------+
  | 14     | AnimatedTile[]  | N/A  |                              |
  +--------+-----------------+------+------------------------------+
  | N/A    | TileMapObject[] | N/A  |                              |
  +--------+-----------------+------+------------------------------+
  | N/A    | TileMapLayer[]  | N/A  |                              |
  +--------+-----------------+------+------------------------------+

  Other structs:

  +-------------+------------------+-------------------------------+
  | Name        | Data Type        | Description                   |
  +=============+==================+===============================+
  |                          AnimatedTile                          |
  +-------------+------------------+-------------------------------+
  | is_playing  | unsigned char    | Should the animation playing? |
  +-------------+------------------+-------------------------------+
  | name        | char[8]          | Name of animation             |
  +-------------+------------------+-------------------------------+
  | count       | unsigned short   | Frame count                   |
  +-------------+------------------+-------------------------------+
  | frame       | short[4 * count] | Store count time of tuple     |
  |             |                  | (x, y, w, h)                  |
  +-------------+------------------+-------------------------------+
  |                         TileMapObject                          |
  +-------------+------------------+-------------------------------+
  | type        | unsigned char    | Object type (point or rect)   |
  +-------------+------------------+-------------------------------+
  | flag        | unsigned char    | A 8 bit flag for the object   |
  +-------------+------------------+-------------------------------+
  | class_name  | char[8]          | Class name of the object      |
  +-------------+------------------+-------------------------------+
  | object_name | char[8]          | Name of the object            |
  +-------------+------------------+-------------------------------+
  | data        | short[4]         | For point: store (x, y, 0, 0) |
  |             |                  | For rect: store (x, y, w, h)  |
  +-------------+------------------+-------------------------------+
  |                          TileMapLayer                          |
  +-------------+------------------+-------------------------------+
  | area        | short[4]         | A (x, y, w, h) tuple          |
  +-------------+------------------+-------------------------------+
  | data        | short[]          | The size must be              |
  |             |                  | area.w * area.h               |
  +-------------+------------------+-------------------------------+

*/

#include "tilemap.h"
#include "../resources/assets.h"
#include "../resources/loader.h"
#include <string.h>

TileSet* default_tileset = NULL;

void InitMapSystem() {
    default_tileset = (TileSet*)malloc(sizeof(TileSet));
    default_tileset->texture =
        LoadTexture(tilesets_png_content, sizeof(tilesets_png_content));
    default_tileset->first_index = 1;
}

void QuitMapSystem() {
    SDL_DestroyTexture(default_tileset->texture);
    free(default_tileset);
}

TileMap* LoadTileMap(const unsigned char* data, size_t size) {
    TileMap* map = (TileMap*)calloc(1, sizeof(TileMap));
    map->tileset_count = 1;
    map->tileset = default_tileset;
    SDL_RWops* map_data = SDL_RWFromConstMem(data, size);
    char header[3];
    SDL_RWread(map_data, header, sizeof(char), 3);
    if (strncmp(header, "MAP", 3)) {
        SDL_RWclose(map_data);
        free(map);
        return NULL;
    }
    unsigned char version;
    SDL_RWread(map_data, &version, sizeof(unsigned char), 1);
    if (version != 1) {
        SDL_RWclose(map_data);
        free(map);
        return NULL;
    }
    unsigned short tile_size[2];
    SDL_RWread(map_data, tile_size, sizeof(unsigned short), 2);
    map->tile_width = tile_size[0];
    map->tile_height = tile_size[1];
    unsigned short count[3];
    SDL_RWread(map_data, &count, sizeof(unsigned short), 3);
    map->animated_tile_count = count[0];
    map->animated_tile =
        (AnimatedTile*)calloc(map->animated_tile_count, sizeof(AnimatedTile));
    map->object_count = count[1];
    map->object =
        (TileMapObject*)calloc(map->object_count, sizeof(TileMapObject));
    map->layer_count = count[2];
    map->layer = (TileMayLayer*)calloc(map->layer_count, sizeof(TileMayLayer));
    for (size_t i = 0; i < map->animated_tile_count; ++i) {
        unsigned char is_playing;
        SDL_RWread(map_data, &is_playing, sizeof(unsigned char), 1);
        map->animated_tile[i].is_playing = is_playing;
        char name[8];
        SDL_RWread(map_data, name, sizeof(char), 8);
        strncpy(map->animated_tile[i].name, name, 8);
        unsigned short count;
        SDL_RWread(map_data, &count, sizeof(unsigned short), 1);
        map->animated_tile[i].count = count;
        map->animated_tile[i].frame =
            (SDL_Rect*)calloc(map->animated_tile[i].count, sizeof(SDL_Rect));
        for (size_t j = 0; j < map->animated_tile[i].count; ++j) {
            short rect[4];
            SDL_RWread(map_data, rect, sizeof(short), 4);
            map->animated_tile[i].frame[j] =
                (SDL_Rect){rect[0], rect[1], rect[2], rect[3]};
        }
    }
    for (size_t i = 0; i < map->object_count; ++i) {
        unsigned char type_and_flag[2];
        SDL_RWread(map_data, type_and_flag, sizeof(unsigned char), 2);
        map->object[i].type = type_and_flag[0];
        map->object[i].flag = type_and_flag[1];
        char name[8];
        SDL_RWread(map_data, name, sizeof(char), 8);
        strncpy(map->object[i].class_name, name, 8);
        SDL_RWread(map_data, name, sizeof(char), 8);
        strncpy(map->object[i].object_name, name, 8);
        short data[4];
        SDL_RWread(map_data, data, sizeof(short), 4);
        if (map->object[i].type == OBJECT_TYPE_POINT) {
            map->object[i].data.point = (SDL_Point){data[0], data[1]};
        } else {
            map->object[i].data.rect =
                (SDL_Rect){data[0], data[1], data[2], data[3]};
        }
    }
    for (size_t i = 0; i < map->layer_count; ++i) {
        short area[4];
        SDL_RWread(map_data, area, sizeof(area), 4);
        map->layer[i].area = (SDL_Rect){area[0], area[1], area[2], area[3]};
        size_t length = map->layer[i].area.w * map->layer[i].area.h;
        map->layer[i].data = (int*)calloc(length, sizeof(int));
        for (size_t j = 0; j < length; ++j) {
            short num;
            SDL_RWread(map_data, &num, sizeof(short), 1);
            map->layer[i].data[j] = num;
        }
    }
    SDL_RWclose(map_data);
    return map;
}

void FreeTileMap(TileMap* map) {
    for (size_t i = 0; i < map->animated_tile_count; ++i) {
        free(map->animated_tile[i].frame);
    }
    for (size_t i = 0; i < map->layer_count; ++i) {
        free(map->layer->data);
    }
    free(map->animated_tile);
    free(map->object);
    free(map->layer);
    free(map);
}
